# Generated by Django 5.2.15 on 2026-07-01 04:55

import django.db.models.deletion
from django.db import migrations, models


def assign_orphan_departments_to_default_site(apps, schema_editor):
    FactorySite = apps.get_model('inventory', 'FactorySite')
    FactoryDepartment = apps.get_model('inventory', 'FactoryDepartment')
    orphans = FactoryDepartment.objects.filter(factory_site__isnull=True)
    if not orphans.exists():
        return
    site, _ = FactorySite.objects.get_or_create(
        code='SITE-DEFAULT',
        defaults={
            'title': 'Varsayılan Fabrika Tesisi',
            'industry_type': 'generic',
            'inventory_panel_title': 'Bölüm Envanteri',
            'department_label': 'Bölüm',
            'zone_label': 'Alt Alan',
            'is_active': True,
        },
    )
    orphans.update(factory_site=site)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_assetqrtag_erpconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tesis Başlığı')),
                ('short_name', models.CharField(blank=True, max_length=60, verbose_name='Kısa Ad')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Tesis Kodu')),
                ('industry_type', models.CharField(choices=[('textile', 'Tekstil'), ('food', 'Gıda & İçecek'), ('automotive', 'Otomotiv'), ('chemical', 'Kimya & Plastik'), ('electronics', 'Elektronik'), ('pharma', 'İlaç & Sağlık'), ('metal', 'Metal & Makine'), ('logistics', 'Lojistik & Depo'), ('energy', 'Enerji'), ('paper', 'Kağıt & Ambalaj'), ('generic', 'Genel Endüstri'), ('custom', 'Özel Sektör Tanımı')], db_index=True, default='generic', max_length=30, verbose_name='Sektör')),
                ('custom_industry_label', models.CharField(blank=True, max_length=80, verbose_name='Özel Sektör Adı')),
                ('customer_name', models.CharField(blank=True, max_length=120, verbose_name='Müşteri')),
                ('portfolio_code', models.CharField(blank=True, max_length=40, verbose_name='Portföy Kodu')),
                ('inventory_panel_title', models.CharField(default='Bölüm Envanteri', max_length=120, verbose_name='Envanter Panel Başlığı')),
                ('department_label', models.CharField(default='Bölüm', max_length=60, verbose_name='Bölüm Etiketi')),
                ('zone_label', models.CharField(default='Alt Alan', max_length=60, verbose_name='Alt Alan Etiketi')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Şehir')),
                ('country', models.CharField(default='Türkiye', max_length=80, verbose_name='Ülke')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
            ],
            options={
                'verbose_name': 'Fabrika Tesisi',
                'verbose_name_plural': 'Fabrika Tesisleri',
                'ordering': ['customer_name', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='factorydepartment',
            options={'ordering': ['factory_site__title', 'department_type', 'name'], 'verbose_name': 'Fabrika Departmanı', 'verbose_name_plural': 'Fabrika Departmanları'},
        ),
        migrations.AlterField(
            model_name='factorydepartment',
            name='code',
            field=models.CharField(max_length=40, verbose_name='Kod'),
        ),
        migrations.CreateModel(
            name='DepartmentInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Envanter Başlığı')),
                ('category_label', models.CharField(blank=True, max_length=100, verbose_name='Özel Kategori')),
                ('item_type', models.CharField(choices=[('it_asset', 'IT Varlık'), ('network', 'Ağ Cihazı'), ('endpoint', 'Endpoint/PC'), ('production', 'Üretim Ekipmanı'), ('tool', 'El Aleti/Kalite'), ('consumable', 'Sarf Malzeme'), ('software', 'Yazılım/Lisans'), ('vehicle', 'Araç/Forklift'), ('furniture', 'Mobilya/Donanım'), ('other', 'Diğer')], db_index=True, default='other', max_length=30, verbose_name='Kalem Tipi')),
                ('reference_code', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Referans Kodu')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Seri No')),
                ('asset_tag', models.CharField(blank=True, max_length=80, verbose_name='Varlık Etiketi')),
                ('barcode', models.CharField(blank=True, max_length=80, verbose_name='Barkod')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Üretici')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='Tedarikçi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('unit', models.CharField(default='adet', max_length=30, verbose_name='Birim')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('spare', 'Yedek'), ('maintenance', 'Bakımda'), ('planned', 'Planlanan'), ('retired', 'Emekli')], db_index=True, default='active', max_length=20, verbose_name='Durum')),
                ('location_note', models.CharField(blank=True, max_length=150, verbose_name='Fiziksel Konum')),
                ('owner_name', models.CharField(blank=True, max_length=120, verbose_name='Sorumlu')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_inventory_items', to='inventory.cameradevice', verbose_name='Kamera')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_inventory_items', to='inventory.consumableitem', verbose_name='Sarf Stok')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.factorydepartment', verbose_name='Bölüm')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_inventory_items', to='inventory.device', verbose_name='Ağ Cihazı')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_inventory_items', to='inventory.endpointdevice', verbose_name='Endpoint')),
                ('it_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_inventory_items', to='inventory.itasset', verbose_name='IT Varlık')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_inventory_items', to='inventory.printerfleetitem', verbose_name='Yazıcı')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.factoryzone', verbose_name='Alt Alan')),
                ('factory_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.factorysite', verbose_name='Fabrika Tesisi')),
            ],
            options={
                'verbose_name': 'Bölüm Envanter Kalemi',
                'verbose_name_plural': 'Bölüm Envanter Kalemleri',
                'ordering': ['factory_site', 'department', 'sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='factorydepartment',
            name='factory_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='inventory.factorysite', verbose_name='Fabrika Tesisi'),
        ),
        migrations.AlterUniqueTogether(
            name='factorydepartment',
            unique_together={('factory_site', 'code')},
        ),
        migrations.RunPython(assign_orphan_departments_to_default_site, migrations.RunPython.noop),
    ]
