# Generated by Django 5.2.15 on 2026-07-01 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_factorysite_departmentinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryconnection',
            name='auto_provision_users',
            field=models.BooleanField(default=False, verbose_name='OmniOps Kullanıcısı Oluştur'),
        ),
        migrations.AddField(
            model_name='directoryconnection',
            name='azure_tenant_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='Azure Tenant ID'),
        ),
        migrations.AddField(
            model_name='directoryconnection',
            name='bind_password',
            field=models.CharField(blank=True, max_length=500, verbose_name='Bind Parolası / Client Secret'),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='factory_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_connections', to='inventory.factorysite', verbose_name='Hedef Fabrika Tesisi'),
        ),
        migrations.AddField(
            model_name='erpconnection',
            name='sync_to_cmdb',
            field=models.BooleanField(default=True, verbose_name='CMDB/Envantere Yaz'),
        ),
        migrations.CreateModel(
            name='OTConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Bağlantı Adı')),
                ('ot_type', models.CharField(choices=[('mes_rest', 'MES REST API'), ('scada_rest', 'SCADA REST API'), ('opc_gateway', 'OPC-UA Gateway (REST)'), ('mqtt_bridge', 'MQTT Bridge (REST)'), ('generic', 'Genel REST')], db_index=True, default='mes_rest', max_length=30, verbose_name='OT Tipi')),
                ('base_url', models.URLField(max_length=500, verbose_name='Sunucu URL')),
                ('assets_path', models.CharField(default='/api/assets', max_length=200, verbose_name='Varlık API Yolu')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key / Token')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Senkronizasyon Aktif')),
                ('sync_to_inventory', models.BooleanField(default=True, verbose_name='Bölüm Envanterine Yaz')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Sync')),
                ('last_sync_status', models.CharField(choices=[('never', 'Hiç Senkronize Edilmedi'), ('healthy', 'Sağlıklı'), ('warning', 'Uyarı'), ('error', 'Hata')], db_index=True, default='never', max_length=20, verbose_name='Sync Durumu')),
                ('last_sync_message', models.TextField(blank=True, verbose_name='Son Sync Mesajı')),
                ('records_synced', models.PositiveIntegerField(default=0, verbose_name='Son Sync Kayıt Sayısı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('factory_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_connections', to='inventory.factorysite', verbose_name='Fabrika Tesisi')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_connections', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'OT/MES Bağlantısı',
                'verbose_name_plural': 'OT/MES Bağlantıları',
                'ordering': ['factory_site__title', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ERPExternalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_model', models.CharField(db_index=True, max_length=80, verbose_name='Harici Model')),
                ('external_id', models.CharField(db_index=True, max_length=80, verbose_name='Harici ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Ham Veri')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Son Eşleme')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_records', to='inventory.erpconnection', verbose_name='ERP Bağlantısı')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_records', to='inventory.consumableitem', verbose_name='Sarf Stok')),
                ('factory_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_records', to='inventory.factorysite', verbose_name='Fabrika Tesisi')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_records', to='inventory.departmentinventoryitem', verbose_name='Bölüm Envanteri')),
                ('it_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_records', to='inventory.itasset', verbose_name='IT Varlık')),
            ],
            options={
                'verbose_name': 'ERP Harici Kayıt',
                'verbose_name_plural': 'ERP Harici Kayıtlar',
                'ordering': ['-synced_at', 'title'],
                'unique_together': {('connection', 'external_model', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='OTAssetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=120, verbose_name='Harici ID')),
                ('tag_name', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Tag/PLC Adresi')),
                ('title', models.CharField(max_length=200, verbose_name='Varlık Adı')),
                ('asset_type', models.CharField(blank=True, max_length=80, verbose_name='OT Varlık Tipi')),
                ('status', models.CharField(choices=[('online', 'Çevrimiçi'), ('offline', 'Çevrimdışı'), ('maintenance', 'Bakımda'), ('unknown', 'Bilinmiyor')], db_index=True, default='unknown', max_length=20, verbose_name='Durum')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Ham Veri')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Son Eşleme')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_assets', to='inventory.factorydepartment', verbose_name='Bölüm')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_records', to='inventory.departmentinventoryitem', verbose_name='Envanter Kalemi')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_records', to='inventory.otconnection', verbose_name='OT Bağlantısı')),
            ],
            options={
                'verbose_name': 'OT Varlık Kaydı',
                'verbose_name_plural': 'OT Varlık Kayıtları',
                'ordering': ['connection', 'title'],
                'unique_together': {('connection', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='UserFactorySiteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('viewer', 'Görüntüleyici'), ('operator', 'Operatör'), ('admin', 'Tesis Yöneticisi')], db_index=True, default='viewer', max_length=20, verbose_name='Erişim Seviyesi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('factory_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='inventory.factorysite', verbose_name='Fabrika Tesisi')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_site_access', to=settings.AUTH_USER_MODEL, verbose_name='Yetki Veren')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_site_access', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Tesis Erişim Yetkisi',
                'verbose_name_plural': 'Tesis Erişim Yetkileri',
                'ordering': ['factory_site__title', 'user__username'],
                'unique_together': {('user', 'factory_site')},
            },
        ),
    ]
